
version: '3.9'

networks:
  app-network:
    driver: bridge
    name: app-network

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "ConversionDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "UnitsDBPass"
    networks:
      - app-network

  unitsconverter-webapi:
    build:
      # image: conversionapi
      context: ./Backend
    expose:
      - 5141
    ports:
      - "5141:5141"
    links:
      - db
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      # image: conversionfrontend
      context: ./frontend/conversion-app
    ports:
      - "8080:80"
    depends_on:
      - unitsconverter-webapi
    networks:
      - app-network
