


name: publish to Github registry

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Github Container registry
        uses: docker/login-action@v1

        with:
          registry: ghcr.ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the UnitsConversion app docker image
        run: |
          docker build . --tag ghcr.io/tobyononaku/units-conversion-gcr:latest
          docker push ghcr.io/tobyononaku/units-conversion-gcr:latest
